FROM node:24-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV SQLITE_DB_PATH=/data/artchew.sqlite

COPY dist/apps/apigee/package*.json ./
RUN npm ci --omit=dev

COPY dist/apps/apigee ./

EXPOSE 3000

CMD ["node", "main.js"]
