import { Providers } from '@artchew/artchew-components';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { GetInTouch } from '../components/GetInTouch';
import './global.scss';
import './variables.scss';

export const metadata = {
  title: 'Welcome to artchew',
  description: 'Generated by create-nx-workspace',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Afacad:ital,wght@0,400..700;1,400..700&family=Protest+Strike&display=swap" />
      </head>
      <body>
        <Providers>
          <Header />

          <main>{children}</main>

          <Footer />

          <GetInTouch />
        </Providers>
      </body>
    </html>
  );
}
