FROM node:24-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=4200
ENV API_INTERNAL_URL=http://api:3000

COPY package*.json ./
RUN npm ci --omit=dev

COPY apps/artchew/.next ./apps/artchew/.next
COPY apps/artchew/public ./apps/artchew/public
COPY apps/artchew/next.config.js ./apps/artchew/next.config.js

EXPOSE 4200

CMD ["./node_modules/.bin/next", "start", "apps/artchew", "-p", "4200", "-H", "0.0.0.0"]
